#!/usr/bin/python
from time import sleep
from flask import Flask
from waitress import serve
import os.path
import 

RUN mkdir -p /root/.ssh/ && \
    echo "$SSH_KEY" > /root/.ssh/id_rsa && \
    chmod -R 600 /root/.ssh/ && \
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

app = Flask(__name__)

jmx_file_directory="/docker-jmeter/"
jmx_reports_path="/docker-jmeter/tests/results/*"
volume_mount_directory="/tmp/jmeter-report"

def jmeter_test(jmx_file_name):
    jmx_file_path=jmx_file_directory+jmx_file_name

    if os.path.exists(jmx_file_path):
        subprocess.call(["/docker-jmeter/jmeter-tests.sh", jmx_file_path])
        subprocess.call(["cp", "-Rf", jmx_reports_path, volume_mount_directory])

        return "Report Generated"
        #sleep(15)
        #content=get_file('/docker-jmeter/tests/results/index.html')
        #return Response(content, mimetype="text/html")
    else:
        return "JMX file not found"

@app.route('/')
def initial_route():
    return "Provide the JMX File name in the url path"


@app.route('/<jmx_filename>')
def jmx_file_name(jmx_filename):
    res= jmeter_test(jmx_filename)
    return res

if __name__ == '__main__':
    #app.run(debug=True)
    serve(app, host="0.0.0.0", port=8080)
